version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  celery:
      build: .
      command: celery -A backend.app.celery_tasks worker --loglevel=INFO -E
      env_file:
        - .env
      depends_on:
        - postgres
        - redis

  fast_api:
    build: .
    command: uvicorn backend.app.endpoint:app --host 0.0.0.0
    container_name: backend_app
    env_file:
      - .env
    depends_on:
      - postgres
      - celery
    ports:
      - "8000:8000"